version: ">= 0.14.0"

formatter: markdown table

content: |-
  [![Tests](https://github.com/netascode/terraform-aci-control-plane-mtu-policy/actions/workflows/test.yml/badge.svg)](https://github.com/netascode/terraform-aci-control-plane-mtu-policy/actions/workflows/test.yml)

  # Terraform ACI Control Plane MTU Policy Module

  Description

  Location in GUI:
  `System` » `System Settings` » `Control Plane MTU`

  ## Examples

  ```hcl
  {{ include "./examples/complete/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Resources }}

output:
  file: README.md
  mode: replace

sort:
  enabled: false